services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: benca_sql
    restart: unless-stopped
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "${ACCEPT_EULA:-Y}"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./database/init.sql:/init.sql
      - ./start.sh:/start.sh
    command: ["/bin/bash", "/start.sh"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    networks:
      - app_network  



  cssportal_app:
    build: 
      context: ./CSS        
      dockerfile: Dockerfile
    container_name: cssportal_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=benca_sql;Database=HRDB;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "8080:8080"
    # volumes:
    #   - ./CSS:/app 
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - app_network
  

  # -----------------------------
  # Nginx Proxy Service
  # -----------------------------
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: css-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - cssportal_app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - ./nginx/conf.d/frontend.conf:/etc/nginx/conf.d/frontend.conf:ro
    networks:
      - app_network


volumes:
  sql_data:

networks:
  app_network:
    driver: bridge